### ISSUE TITLE
Ignores rest of ion-buttons

### ISSUE THREAD

**Issue by blahblehblah** [RaschidJFR/ionic-header-parallax#12]
This only shows the first ion-button on the header and ignores the rest.

**Comment by Nitin-Daddikar** [comment]
@RaschidJFR When can we expect this enhancement ? Because its a import kind of functionality that is missed. Please it will be very helpful

**Comment by RaschidJFR** [comment]
Hey, I'm upgrading the package and would like to incorporate some of the enhancement proposals. Would you mind elaborating on this issue?

**Comment by RaschidJFR** [comment]
This has been addressed in #39  for version `v3.0.1` of the package.
