### ISSUE TITLE
parallax not working

### ISSUE THREAD

**Issue by bhandaribhumin** [RaschidJFR/ionic-header-parallax#13]
not able to see image 

![Screen Shot 2019-10-17 at 3 50 44 PM](https://user-images.githubusercontent.com/3336047/67000708-f59ef580-f0f5-11e9-89c2-21287892d050.png)

```
import { IonicHeaderParallaxModule } from 'ionic-header-parallax';

const routes: Routes = [
  {
    path: '',
    component: ArticlePage
  }
];

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    RouterModule.forChild(routes),
    IonicHeaderParallaxModule
  ],
  declarations: [ArticlePage]
})
export class BrowsePageModule { }

```

**Comment by RaschidJFR** [comment]
Any error in Console? Have you tried the [Stackblitz Demo](https://stackblitz.com/github/raschidjfr/ionic-header-parallax)?

**Comment by klishey** [comment]
Same issue here, even the [StackBlitz Demo](https://stackblitz.com/github/raschidjfr/ionic-header-parallax) is not working anymore

**Comment by klishey** [comment]
> Same issue here, even the [StackBlitz Demo](https://stackblitz.com/github/raschidjfr/ionic-header-parallax) is not working anymore

It says: Error: Parallax directive requires an <ion-content> element on the page to work.

**Comment by RaschidJFR** [comment]
It works. I don't know why the first time it fails on Stackblitz, but if you change whatever line just to make the app reload it works alright (just type a white space in the code and it will load correctly).

**Comment by klishey** [comment]
My bad it's working alright, Is there a way to exclude the title in the front of the image? Then only show it after the parallax collapse?

**Comment by RaschidJFR** [comment]
Sure, just set de property `titleColor` to `"transparent"`:

```
<ion-header parallax titleColor="transparent" ...>
```
