### ISSUE TITLE
stackblitz example not working

### ISSUE THREAD

**Issue by NabiilahDatabase** [RaschidJFR/ionic-header-parallax#16]
please check your slackblitz code example
https://stackblitz.com/github/raschidjfr/ionic-header-parallax

its not working man

**Comment by RaschidJFR** [comment]
Can you be more specific? It works, just make sure you reload the right panel.

**Comment by RaschidJFR** [comment]
The stackblitz project keeps showing this:
![image](https://user-images.githubusercontent.com/8172495/144270199-a16d0ea1-e45c-41bd-aa0f-f4ebe193c4ae.png)

I found this related [thread](https://stackoverflow.com/questions/60492752/stackblitz-doesnt-work-with-angular-project-with-internal-library) on stackoverflow.

Note to myself: It would be a good idea to create a new demo folder in the repo to isolate the demo app.
