### ISSUE TITLE
Not working for ionic4

### ISSUE THREAD

**Issue by elmartino** [RaschidJFR/ionic-header-parallax#2]
Would it be possible to make this ionic4 compatible?

**Comment by RaschidJFR** [comment]
Hi @elmartino , I've just got familiar with v4 so hopefully I'll make an update soon.

**Comment by RaschidJFR** [comment]
Version [2.0.0](https://github.com/RaschidJFR/ionic-header-parallax/releases) for ionic 4 is now ready, check it out.
