### ISSUE TITLE
Routing glitch

### ISSUE THREAD

**Issue by mteera** [RaschidJFR/ionic-header-parallax#22]
When routing to a page that has a parallax header the header shows up instantly rather than slides in like the rest of the page. When routing back there doesn't appear to be any issue. I've tried it on both NavController and Router services. Any recommendation?

**Comment by RaschidJFR** [comment]
Hi @mteera thanks for reporting. Sorry for my late reply. Can you share your output of `$ ionic info`?

**Comment by mteera** [comment]
Hello, here is my `$ ionic info`:

Ionic:

   Ionic CLI                     : 6.2.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.8
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 15 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   ios-sim : 8.0.2
   NodeJS  : v12.16.1 (/usr/local/bin/node)
   npm     : 6.14.2
   OS      : macOS Catalina
   Xcode   : Xcode 11.3.1 Build version 11C505


  ───────────────────────────────────────────────

     Ionic CLI update available: 6.2.1 → 6.4.0
         Run npm i -g @ionic/cli to update

  ───────────────────────────────────────────────

**Comment by RaschidJFR** [comment]
Thanks for the info. I see this happens in iOS transitions. I did some superficial tests but got no luck. I guess we'll have to dive into the animation system used for transitions. Also, now that Ionic 5 is out maybe it would be a good idea to do a whole re-engineering. Unfortunately I don't know when I'll be able to.

**Comment by RaschidJFR** [comment]
Closing this as stale now that there is a newer version of Ionic and the package.
