### ISSUE TITLE
dynamic error

### ISSUE THREAD

**Issue by franciscoalex2407** [RaschidJFR/ionic-header-parallax#3]
I can not put the url dynamically, it goes incomplete

**Comment by RaschidJFR** [comment]
Can you share some code @sigautomacao  so I can take a look?

**Comment by RaschidJFR** [comment]
I'll close this due to inactivity. Version [2.0.0](https://github.com/RaschidJFR/ionic-header-parallax/releases) for ionic 4 is now ready, check it out.

**Comment by simbig** [comment]
I have the same error here. The maximum length of a path that is not set by a hardcorded URL but by a variable seems to be a length of 30.

assets/img/categoriesHeaders/sail will be truncated to assets/img/categoriesHeaders/s
<img width="435" alt="Bildschirmfoto 2020-01-26 um 16 01 06" src="https://user-images.githubusercontent.com/26680884/73137103-27a8e780-4055-11ea-9484-6eddb38298ff.png">

**Comment by RaschidJFR** [comment]
Sounds strange... I've just tested this image [https://raw.githubusercontent.com/RaschidJFR/ngx-googlemaps-tracking-view/master/img/demo1.jpg](https://raw.githubusercontent.com/RaschidJFR/ngx-googlemaps-tracking-view/master/img/demo1.jpg) and it works ok on the [PlayGround](https://stackblitz.com/github/raschidjfr/ionic-header-parallax?file=src%2Fapp%2Fhome%2Fhome.page.html)
