### ISSUE TITLE
dynamically add url for imageurl not work 

### ISSUE THREAD

**Issue by ghost** [RaschidJFR/ionic-header-parallax#33]
hi i am using 
ionic-header-parallax i want to use a varriable to show image in header and it doesnt work. The maximum length of a path that is not set by a hardcorded URL but by a variable seems to be a length of 30.when i used url it is work but when used a varrible it dosnt work....

<img width="655" alt="Screen Shot 1399-07-11 at 21 48 47" src="https://user-images.githubusercontent.com/54864147/94956507-2475cd80-04f9-11eb-9532-fc68b9fd3322.png">

<img width="655" alt="Screen Shot 1399-07-11 at 21 49 37" src="https://user-images.githubusercontent.com/54864147/94956544-35264380-04f9-11eb-96ac-5169275f06ba.png">

dont show complete link path in imageurl when use varriable
<img width="655" alt="Screen Shot 1399-07-11 at 21 51 19" src="https://user-images.githubusercontent.com/54864147/94956715-833b4700-04f9-11eb-9486-c7dd89172b4c.png">

please help me

**Comment by RaschidJFR** [comment]
Hi. I'm not able to reproduce the issue. Are you sure it's not something else in your code? can you share the `.ts` file?

**Comment by RaschidJFR** [comment]
Closing as stale. Feel free to reopen if needed.
