### ISSUE TITLE
ERROR TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by lenanex** [RaschidJFR/ionic-header-parallax#34]
Hello,

Everything works fine but I'm getting this error message:

ERROR TypeError: Cannot read property 'style' of null
    at DefaultDomRenderer2.setStyle (platform-browser.js:739)
    at ionic-header-parallax.js:68

apparently this line:

this.renderer.setStyle(toolbarTitle, 'pointer-events', 'unset');

Any help ? :)

Thanks for this great module !

**Comment by RaschidJFR** [comment]
Hi. Can you provide a way of reproducing the issue or share some code maybe on [stackblitz](//stackblitz.com) or similar?

**Comment by hakimio** [comment]
@RaschidJFR I am also getting this error with `v3.0.0-dev` of this library, Angular v13 and Ionic v6.
The code I am using is really simple:
```html
<ion-header
    parallax
    imageUrl="/assets/images/some-picture.jpg"
    maximumHeight="300"
    expandedColor="#FFFFFFFF"
    titleColor="#FFFFFF"
>
    <ion-toolbar>
        <ion-title>Event</ion-title>
        <ion-buttons slot="end">
            <ion-button
                color="dark"
                fill="solid"
            >
                Continue
            </ion-button>
            <ion-button id="menu-btn">
                <ion-icon slot="icon-only" ios="ellipsis-horizontal" md="ellipsis-vertical"></ion-icon>
            </ion-button>
        </ion-buttons>
    </ion-toolbar>
</ion-header>

<ion-content class="ion-padding">
    <h3>Foo Bar</h3>
    <p>Foo bar baz.</p>
</ion-content>
```

![image](https://user-images.githubusercontent.com/768105/143214870-2aa9cea9-1d7d-449e-86bb-9f7e4936a83e.png)

The error happens on [this line](https://github.com/RaschidJFR/ionic-header-parallax/blob/8c387ee5bde4b9e4157854f479c75eb4b2b2f3f9/projects/ionic-header-parallax/src/lib/parallax.directive.ts#L77) and it's not triggered every time. Maybe the timeout should be increased?

Also, any idea why buttons with `slot="end"` are shown in the start of the toolbar and why those same buttons disappear when I have other buttons in `slot="start"`?
