### ISSUE TITLE
Ionic v6 and Angular v13

### ISSUE THREAD

**Issue by hakimio** [RaschidJFR/ionic-header-parallax#38]
Any plans to update the project for Ionic v6 and Angular v13?

**Comment by RaschidJFR** [comment]
There is an experimental version with Ionic5-Angular12 still unreleased. You can try it by installing it with `npm i ionic-header-parallax@next`.

**Comment by hakimio** [comment]
I was using it and it works with issues mentioned in #34.

**Comment by RaschidJFR** [comment]
I've just released `3.0.1` which fixes #34 . Haven't tested it with Ionic 6 but you can give it a try @hakimio .
I don't think I'll work on that before Ionic 6 is officially released.

**Comment by hakimio** [comment]
@RaschidJFR since the library works just as well with Angular 13 as it does with Angular 12, maybe you could just extend the peer dependency range? Something like the following maybe:
```json
    "@angular/common": ">=12.0.0",
    "@angular/core": ">=12.0.0"
```

**Comment by RaschidJFR** [comment]
Thanks for testing @hakimio . Would you care to raise a PR for this?

**Comment by hakimio** [comment]
@RaschidJFR I have opened PR #42.
