### ISSUE TITLE
header was not accepted attributed

### ISSUE THREAD

**Issue by rajkumargond** [RaschidJFR/ionic-header-parallax#4]

**Comment by rajkumargond** [comment]
<ion-header parallax 
	[fadeTitle]="true" 
	imageUrl="https://ununsplash.imgix.net/photo-1421091242698-34f6ad7fc088?fit=crop&fm=jpg&h=650&q=75&w=950" 
	maximumHeight="350"
	parallaxColor="#ab26c3">

	<ion-navbar color="secondary">
		<ion-title>My Parallax Header</ion-title>
	</ion-navbar>

</ion-header>

**Comment by RaschidJFR** [comment]
Anything more descriptive than that?

**Comment by RaschidJFR** [comment]
I'll close this due to inactivity. Version [2.0.0](https://github.com/RaschidJFR/ionic-header-parallax/releases) for ionic 4 is now ready, check it out.
