### ISSUE TITLE
String values for height config don't seem to work

### ISSUE THREAD

**Issue by hakimio** [RaschidJFR/ionic-header-parallax#40]
The docs state: ` If the value is a string it will be passed as is (eg: "20rem")`, however it doesn't seem to work in the latest version. Setting `height` to a number seems to work fine but values like `35vh`, `35%` or simply `350px` don't seem to be applied correctly. The image height becomes the same as the toolbar height in that case.

Library version: `3.0.2`
Ionic: `6`
Angular: `13`

@RaschidJFR 

EDIT: same issue can be reproduced in the demo app.

**Comment by hakimio** [comment]
Might have to use [this css unit converter](https://stackoverflow.com/a/66569574/3529279) to fix this.

**Comment by hakimio** [comment]
@RaschidJFR 
It seems following code lines are problematic:
- [updateProgress()](https://github.com/RaschidJFR/ionic-header-parallax/blob/08b1d958f8be681d3f772dabf8cae75aa2d1a6f2/projects/ionic-header-parallax/src/lib/ionic-header-parallax.directive.ts#L155)
- [progressLayerHeight()](https://github.com/RaschidJFR/ionic-header-parallax/blob/08b1d958f8be681d3f772dabf8cae75aa2d1a6f2/projects/ionic-header-parallax/src/lib/ionic-header-parallax.directive.ts#L162)

You are trying to convert string to number with `+this.height` which results in `NaN` in case height is CSS unit like `35vh`.

**Comment by RaschidJFR** [comment]
Got it. I'll have a look at this over the weekend, but feel free to shoot a PR if you feel like tackling this.
