### ISSUE TITLE
"Height" input changes are not applied correctly

### ISSUE THREAD

**Issue by hakimio** [RaschidJFR/ionic-header-parallax#41]
Changing `height` input value during runtime doesn't seem to work. It only correctly applies the initial value.
It's an issue if you want to have different image height for different window height.

**Comment by RaschidJFR** [comment]
The directive loads the height only one time, during initialization. If you wanted to change the height according to window height you should use relative units like `%`. I've seen there is an open issue for this in #40 so I'm closing this as it depends on that one.

**Comment by hakimio** [comment]
@RaschidJFR Ok, let's say I am using `vh` or `%` units. Changing window size, will cause image to be resized. Will the `scroll progress` be updated correctly in that case as well? As far as I can see, it's only updated on scroll event and browser resize doesn't cause this event to be fired.
