### ISSUE TITLE
support to angular 14

### ISSUE THREAD

**Issue by aurelienpenot** [RaschidJFR/ionic-header-parallax#47]
**npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @0.0.1
npm ERR! Found: @angular/common@14.2.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=12.0.0 <14.0.0" from ionic-header-parallax@3.1.0
npm ERR! node_modules/ionic-header-parallax
npm ERR!   ionic-header-parallax@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home//.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home//.npm/_logs/2022-09-05T09_40_51_103Z-debug-0.log**

Can you please update the plugin for angular v14 ?

**Comment by adeldx** [comment]
+1

**Comment by LSDCF** [comment]
> +1

I solve it by adding a directive in my app of the ionic-header-parallax.directive.ts and it works.
I even modified it so i can make a component of the header to import it on all my pages :)

**Comment by RaschidJFR** [comment]
Fixed in recent release [v5.0.0](https://github.com/RaschidJFR/ionic-header-parallax/releases/tag/5.0.0)
