### ISSUE TITLE
Cannot find name "ParallaxDirective"

### ISSUE THREAD

**Issue by kabubi** [RaschidJFR/ionic-header-parallax#6]
Hi, im using this:

Ionic:

   Ionic CLI          : 5.0.0 (C:\Users\coroleu\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-webview 1.2.1, (and 9 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.2

System:

   NodeJS : v8.11.3 (D:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

And i follow this steps:

https://www.npmjs.com/package/ionic-header-parallax/v/1.0.1

But Visual Studio Code show me this problem:

Cannot find name "ParallaxDirective"

Any idea why?
Thanks

**Comment by RaschidJFR** [comment]
What package version did you install? You should install 1.0.1 like this: `npm i ionic-header-parallax@1.0.1`.

Also, can you post some code of the file that's throwing the error?

**Comment by kabubi** [comment]
Hello Rashid, i use this package: npm i ionic-header-parallax@1.0.1
https://imgur.com/m24FJcI

**Comment by RaschidJFR** [comment]
It looks like you're missing the import. Add this line to your .ts file:

```
import { ParallaxDirective } from 'ionic-header-parallax';
```

**Comment by kabubi** [comment]
Hi again... i dont know what i doing wrong.
I try adding the import on app.module.ts and add this "ParallaxDirective" to declarations but still doesnt work (check image)
https://imgur.com/TbWJcdt
Im using ionic v3

**Comment by RaschidJFR** [comment]
For v3 you have to import `ParallaxDirective` not `IonicHeaderParallaxModule`. Sorry I edited my answer but I guess it was too late. Just change that line it should work ok.

```
import { ParallaxDirective } from 'ionic-header-parallax';
```

**Comment by kabubi** [comment]
Thanks, with that change i dont have any error on VS but when i run on my browser i have this error:
https://imgur.com/FJVuBFG

**Comment by kabubi** [comment]
Thanks, with that change i dont have any error on VS... but i have some errors on my browser emulator:
https://imgur.com/FJVuBFG
https://imgur.com/1LdfmOI
Any ideas what im doing wrong?

**Comment by RaschidJFR** [comment]
Mmm... the implementation of this package is kinda tricky I see now, sorry for that, the v3 is an old project and honestly it's not my best work :/ . I might change it on a free time to give the correct support for v3.

So this is the correct way of implementing it, I didn't do back then but I'll tell you how to do it. Let's create a module for the directive so it works correctly:

1) Create the file `src/directives/directives.module.ts` (or add these lines if it already exists):

```
// directives.module.ts
import { NgModule } from '@angular/core';
import {ParallaxDirective} from 'ionic-header-parallax';

@NgModule({
  declarations: [
    ParallaxDirective
  ],
  exports:[
    ParallaxDirective
  ]
})
export class DirectivesModule {}
```

2. Import directives module in every page you want to use parallax (for example `home.module.ts`):

```
// home.module.ts
import { DirectivesModule } from '../../directives/directives.module'; // <-- or whatever path

@NgModule({
  declarations: [
    HomePage,
  ],
  imports: [
    DirectivesModule,
    ...
```

3. Finally, don't forget to include the styles in a global style like `app.scss` or `variables.scss` (this is the correct path!):

```
@import "../node_modules/ionic-header-parallax/sass/ionic-header-parallax.scss"; //<-- or whatever path into node_modules
```

**Comment by kabubi** [comment]
Thanks, I really appreciate you taking the time to help me.
I did everything you told me but now i have this error...
https://imgur.com/oUW33eL
Im sorry, im really newbie here...

**Comment by RaschidJFR** [comment]
That error means it's working. As it describes, you need to add a `<ion-toolbar>` or `<ion-navbar>` inside your `<ion-header>`:

```
<ion-header parallax>

  <ion-toolbar color="primary">
    <ion-title>
      Your Title
    </ion-title>
  </ion-toolbar>
</ion-header>
```

**Comment by kabubi** [comment]
I have this right now:
https://imgur.com/DbHtsEj

**Comment by RaschidJFR** [comment]
So strange, it seems alright from here. I've just tested all the instructions I gave you and they work ok. The problem must be somewhere else in the code. Is your repo on github? Can I take a look?

**Comment by kabubi** [comment]
Yes, no problem
https://github.com/kabubi/hcdposadas

**Comment by RaschidJFR** [comment]
Good news, I've updated the package to [v1.1.0](https://www.npmjs.com/package/ionic-header-parallax/v/1.1.0). Thanks for sharing your code, I found and fixed some errors for v3.
